server.port=4545

spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal_db

spring.datasource.username=postgres

spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# ============================================================
# EMAIL CONFIGURATION
# ============================================================

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=rohanchavan5604@gmail.com

spring.mail.password=evia ffpz jboz hqob

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true